# Backend: usiamo il Git Gateway, che ora è "potenziato" dal login con Auth0.
backend:
  name: git-gateway
  branch: main

# Localizzazione interfaccia
locale: 'it'

# Percorsi per i file
media_folder: "src/images/uploads"
public_folder: "/images/uploads"

# Struttura dei Contenuti
collections:
  - name: "articoli"
    label: "Articoli"
    folder: "src/articoli"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Immagine", name: "image", widget: "image", optional: true }
      - { label: "Corpo Articolo", name: "body", widget: "markdown" }