# Imposta Netlify come backend per l'autenticazione
backend:
  name: git-gateway
  branch: main # O la tua branch principale

# Localizzazione (opzionale, ma utile)
locale: 'it'

# Percorso per il salvataggio dei file media
media_folder: "src/images/uploads"
public_folder: "/images/uploads"

# Struttura dei tuoi contenuti
collections:
  - name: "articoli" # Identificativo tecnico
    label: "Articoli" # Come appare nel menu del CMS
    folder: "src/articoli" # Dove vengono salvati i nuovi file
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # I campi del modulo di inserimento
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Immagine", name: "image", widget: "image", optional: true }
      - { label: "Testo dell'Articolo", name: "body", widget: "markdown" }