# Backend: usiamo la connessione diretta a GitHub. 
# È il metodo più stabile e raccomandato.
backend:
  name: github
  repo: TiaNotSenpai/LA-GIOVANE-FINO # Inserisci il tuo "utente/repository"
  branch: main # O la tua branch principale

# Localizzazione
locale: 'it'

# Percorsi per le immagini
media_folder: "src/images/uploads"
public_folder: "/images/uploads"

# Struttura dei Contenuti
collections:
  - name: "articoli"
    label: "Articoli"
    folder: "src/articoli"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Immagine", name: "image", widget: "image", optional: true }
      - { label: "Testo dell'Articolo", name: "body", widget: "markdown" }