backend:
  name: git-gateway
  branch: main # O il nome del tuo branch principale, es. master

# Percorso dove salvare le immagini caricate tramite il CMS
media_folder: "src/images/uploads" 
# Percorso pubblico per visualizzare le immagini
public_folder: "/images/uploads" 

# Qui definiamo le nostre "Collezioni" di contenuti
collections:
  # La prima collezione è per gli articoli di istruzione
  - name: "articoli" # Nome tecnico della collezione
    label: "Articoli Istruzione" # Nome visualizzato nel CMS
    folder: "src/articoli" # Dove salvare i file degli articoli
    create: true # Permette di creare nuovi file
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Formato del nome del file (es. 2025-06-22-titolo-articolo)
    fields: # I campi da riempire per ogni articolo
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data Pubblicazione", name: "date", widget: "datetime" }
      - { label: "Immagine di Copertina", name: "image", widget: "image", optional: true }
      - { label: "Testo Articolo", name: "body", widget: "markdown" }
  
  # Potremmo aggiungere qui una collezione per le "News"
  # - name: "news"
  #   label: "Notizie Locali"
  #   folder: "src/news"
  #   ... ecc.