# Backend: dice al CMS di usare il Git Gateway di Netlify per autenticarsi e salvare su GitHub.
backend:
  name: git-gateway
  branch: main # Assicurati che 'main' sia il nome del tuo branch principale

# Localizzazione: usiamo l'italiano per l'interfaccia
locale: 'it'

# Media: dove salvare le immagini caricate tramite il CMS.
media_folder: "src/images/uploads"
public_folder: "/images/uploads"

# Collections: qui definiamo i tipi di contenuti che vuoi gestire.
collections:
  - name: "articoli"
    label: "Articoli (Istruzione)"
    folder: "src/articoli" # Salva i file in questa cartella
    create: true
    slug: "{{slug}}" # Il nome del file sarà il titolo "slugificato" (es. titolo-articolo.md)
    # I campi da compilare per ogni articolo
    fields:
      - { label: "Titolo Articolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Immagine di Copertina", name: "image", widget: "image", optional: true }
      - { label: "Contenuto Principale", name: "body", widget: "markdown" }